<a href="https://colab.research.google.com/github/spectralcodex/shruglife/blob/main/ann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.4.1'

## Part 1 - Data Preprocessing

### Importing the dataset

In [21]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

dataset

RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10000 rows x 14 columns]

### Encoding Categorical data

#### Label Encoding the "Gender" column

In [4]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])


In [5]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


#### One Hot Encoding the "Geography" column

In [22]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [23]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [9]:
print(X_test)

[[0.0 1.0 0.0 ... 1 1 192852.67]
 [1.0 0.0 0.0 ... 1 0 128702.1]
 [0.0 0.0 1.0 ... 1 1 75732.25]
 ...
 [0.0 0.0 1.0 ... 1 0 141533.19]
 [0.0 1.0 0.0 ... 1 1 11276.48]
 [0.0 1.0 0.0 ... 1 0 192950.6]]


### Feature Scaling

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing ANN

In [11]:

ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [12]:
ann.add(tf.keras.layers.Dense(6, activation='relu'))

### Adding the second hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(6, activation='relu'))

### Adding output layer

In [14]:
ann.add(tf.keras.layers.Dense(1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [15]:
# Create an optimizer to calulate the loss/cost function
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics=['accuracy'])

### Training the ANN on the Training Set

In [16]:
ann.fit(x=X_train, y=y_train, epochs=100, batch_size=32)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.6045 - accuracy: 0.7194
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4942 - accuracy: 0.7911
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4743 - accuracy: 0.7878
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4420 - accuracy: 0.8070
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4268 - accuracy: 0.8222
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4184 - accuracy: 0.8219
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4039 - accuracy: 0.8342
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4122 - accuracy: 0.8297
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4023 - accuracy: 0.8362
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3935 - accura

## Part 4 - Marking the predictions and evaluating the model

### Predicting the result of a single observation

In [33]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))

[[0.02760303]]


### Predicting the Test set results

In [36]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the confusion matrix

In [37]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1511   84]
 [ 194  211]]


0.861