<a href="https://colab.research.google.com/github/spectralcodex/shruglife/blob/main/ann_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

## Import libraries

In [3]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [4]:
tf.__version__

'2.4.1'

# Part 1 - Data Preprocessing

## Import dataset

In [8]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
dataset
## Create matrix features and dependent variable vector
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:,-1].values

In [10]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


## Splitting the dataset to training and Test set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Part 2 - Building ANN

### Initializing the ANN

In [12]:
# Initialize model to handle the layers of neurons
ann = tf.keras.models.Sequential() # First layer to recieve input

### Adding the inut layer and the first hidden layer

In [13]:
# 1st Hidden layer with 6 neuros using rectifier activation funtion(weighted_sum calculator)
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the secong hidden layer

In [14]:
# 2nd Hidden layer with 6 neuros using rectifier activation funtion(weighted_sum calculator)
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [15]:
# Output layer with 1 neuros
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling ANN

In [16]:
# Create an optimizer to calulate the loss function
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Predicting the results of the Test Set

In [18]:
ann.fit(x=X_train, y=y_train, epochs=100, batch_size=32)

Epoch 1/100
240/240 [==============================] - 0s 1ms/step - loss: 26.3653
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 26.1921
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 26.6261
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 26.0098
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 26.2151
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 26.1566
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 26.4682
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 26.5468
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 26.5921
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 26.2416
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 26.3340
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - loss: 25.9907
E

## Predicting the results

In [20]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1) ), 1))

[[430.65 431.23]
 [461.59 460.01]
 [465.07 461.14]
 ...
 [472.33 473.26]
 [439.16 438.  ]
 [458.36 463.28]]
